name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev libgdbm-dev libnss3-dev \
          libssl-dev libreadline-dev libffi-dev wget libsqlite3-dev openjdk-17-jdk lld \
          python3-dev autoconf automake libtool pkg-config zlib1g-dev

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install --user buildozer cython==0.29.33 virtualenv

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          yes | buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk

